/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'originalPrice' : IDL.Opt(IDL.Nat),
  'subcategory' : IDL.Text,
  'isOnSale' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({ 'qty' : IDL.Nat, 'product' : Product });
export const CategoryData = IDL.Record({
  'category' : IDL.Text,
  'subcategories' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Bool], []),
  'clearCart' : IDL.Func([IDL.Text], [], []),
  'deploy' : IDL.Func([], [], []),
  'getBestDeals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(CategoryData)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsBySubcategory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'updateCartItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'originalPrice' : IDL.Opt(IDL.Nat),
    'subcategory' : IDL.Text,
    'isOnSale' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'qty' : IDL.Nat, 'product' : Product });
  const CategoryData = IDL.Record({
    'category' : IDL.Text,
    'subcategories' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Bool], []),
    'clearCart' : IDL.Func([IDL.Text], [], []),
    'deploy' : IDL.Func([], [], []),
    'getBestDeals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(CategoryData)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsBySubcategory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'updateCartItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };